---
- name: Ensure ~/.ssh directory exists for each user
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: "0700"

- name: Copy public key to authorized_keys
  ansible.builtin.copy:
    dest: "~/.ssh/authorized_keys"
    content: "{{ ssh_ansible_public_key_bws }}"
    mode: "0600"

- name: Ensure sshd_config is configured according to template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
  notify: Restart ssh